Import-Module activedirectory 

$CSVPath = "C:\powershell\Outputfiles" 
$smtpserver = "exchsrv2.kuits.local" 
$from = "itdept@kuits.com"
$userdetails = Get-ADUser -filter * -searchscope subtree -searchbase " OU=ksl staff,DC=kuits,DC=local" –Properties *
$date = get-date 
$newline = "<br>" 
$body ="" 
$res=""


foreach ($user in $userdetails)
{
    #Get-ChildItem -Path $user.homedirectory -Include .mp3,.mp4,.wma,.wmv,.mov,.mpg,.avi,*.api,.jpg,.jpeg,.png,.gif,.bmp -Recurse `
     #   | select name, fullname | export-csv "c:\stuff\mp3log\$($user.samaccountname).csv" -noType

    $path = "\\kslnas01\folderredirection$\" + $user.samaccountname
    Get-ChildItem -Path $path -Include .mp3,.mp4,.wma,.wmv,.mov,.mpg,.avi,*.api,.jpg,.jpeg,.png,.gif,.bmp -Recurse `
        | select name, fullname | export-csv "c:\stuff\mp3log\$($user.samaccountname).csv" -noType

    #[int]$res=((Get-ChildItem -Path $user.homedirectory -Include .mp3,.wma,.wmv,.mov,.mpg,.avi,*.api `
     #   -Recurse | Measure-Object -Sum Length).Sum / 1MB)

    [int]$res=((Get-ChildItem -Path $path -Include .mp3,.wma,.wmv,.mov,.mpg,.avi,*.api `
        -Recurse | Measure-Object -Sum Length).Sum / 1MB)

    if ($res -gt 1000)
    {
        #$to = $user.emailaddress
        $to = "daneilblank@kuits.com"
        $subject = "Your media files are " + $res + " MB " + "big"
        $body += " Dear " + $($user.givenname) + " " + $($user.surname) + " " + `
            "we have detected some media files on your My Documents Folder " + $newline + $newline
        $body += " This files may include *.mp3,*.wma,*.wmv,*.mov,*.mpg and *.avi " + $newline + $newline
        $body += " Please find an attachment with the location and name of the files" + $newline + $newline
        $body += " If these files are genuine and work related, you don't need to do anything." + $newline + $newline
        $body += " However if the files are not work related please consider deleting them as they are taking space on the company file servers." `
            + $newline + $newline
        $body += " Thank you for playing fair" + $newline + $newline 
        $body += " Message generated by the helpdesk on " + $date + "."

        $outputencoding = [system.Text.Encoding]::UTF8
        Send-MailMessage -smtpServer $smtpserver -from $from -to $to -subject $subject -body $body -Attachments "c:\mp3log\$($user.samaccountname).csv" `
            -bodyashtml -encoding $outputencoding $body="" $subject="" $res="" 
    }
    }